server:
  port: 8090

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# ChatGPT SDK Config
chatglm:
  sdk:
    config:
      # 状态；true = 开启、false 关闭
      enabled: true
      # 官网地址 https://open.bigmodel.cn/
      api-host: https://open.bigmodel.cn/
      # 官网申请 https://platform.openai.com/account/api-keys
      api-Secretkey: 0dc1c9beb3241e6326358bc8078f6e97.Kc7WotuYSEaoUqV8
# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml